name: auto Comment On Issues
on:
  issues:
    types: [opened]
permissions:
  issues: write

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add a comment to the new issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number:context.issue.number,
              owner:context.repo.owner,
              repo:context.repo.repo,
              body:"Thanks for opening this isses! we'll look into it soon."
              })
            

   
    
    
